name: profile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.6  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.jpg
    - assets/images/linkedin.png
    - assets/images/github.png
    - assets/images/instagram.png
